### ISSUE TITLE
User selection looks broken

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#531] opened 2019-03-28 18:02 UTC
See
![Screenshot from 2019-03-28 19-01-53](https://user-images.githubusercontent.com/24682367/55181438-f5f09700-518b-11e9-8de3-04168958c4de.png)
@chrisma Might this be related to #498?

**Comment by chrisma** [comment] 2019-03-28 21:04
Thanks for the noticing! I can't reproduce this currently on my local setup, but the last `dev` deploy wasn't successful (http://hart-deploy.epic-hpi.de/), so the issue might already be fixed in the latest version. I'll fix the deploy tomorrow.

**Comment by chrisma** [comment] 2019-03-29 09:00
Indeed: `GET https://hart-dev.epic-hpi.de/assets/select2.css net::ERR_ABORTED 404 (Not Found)`

**Comment by chrisma** [comment] 2019-03-29 13:41
Fixed: https://github.com/hpi-swt2/vm-portal/commit/dfe0c1dc16ce905bf6fd34fb6bdfee7435f3ebbe

**Closed by chrisma** 2019-03-29 13:41 UTC
Labels: bug

**Comment by BjoernDaase** [comment] 2019-03-29 16:43
> Fixed: [dfe0c1d](https://github.com/hpi-swt2/vm-portal/commit/dfe0c1dc16ce905bf6fd34fb6bdfee7435f3ebbe)

Perfect :+1:
